FROM ubuntu:18.04

# Dependencias
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    qt5-default \
    sudo \
    protobuf-compiler \
    qtdeclarative5-dev \
    libeigen3-dev \
    libprotobuf-dev \
    libdc1394-22 \
    libdc1394-22-dev \
    libv4l-0 \
    libopencv-dev \
    freeglut3-dev \
    python3 \    
    && apt-get clean
